rootUrl: 'http://localhost:3000/'
gridUrl: 'http://127.0.0.1:4444/wd/hub'

browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome

system:
  plugins:
    'html-reporter/gemini':
      enabled: true
      path: 'reports/gemini'


#compositeImage: true
#sessionsPerBrowser: 2
tolerance: 3.5
windowSize: 1600x2400
