version: 2

groups:
  code-review:
    required: 2 # 2 of the reviewers must approve the PR
    reset_on_push:
      enabled: false # Approval status doesn't reset to "pending" when new commits are pushed to a PR
    author_approval:
      ignored: true # PR author's approval doesn't count towards the required # of approvals
    approve_by_comment:
      enabled: true
      approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
      reject_regex: '^(Rejected|:-1:)'
    teams:
      - clarity-maintainers
    conditions:
      branches:  # only need to review if merging into master
          - master
      files:
        exclude:  # don't need to review if the PR only changes these files
          - ".pullapprove.yml"  # great for ensuring pullapprove settings are approved
