const commitLintConfig = require('@commitlint/config-conventional');

const scopes = [
  'angular',
  'angular:form',
  'angular:schematics',
  'angular:datagrid',
  'angular:vertical-nav',
  'angular:timeline',
  'a11y',
  'accordion',
  'alert',
  'badge',
  'build',
  'button',
  'card',
  'checkbox',
  'color',
  'combobox',
  'datagrid',
  'datalist',
  'date-picker',
  'dropdown',
  'form',
  'form-group',
  'grid',
  'header',
  'i18n',
  'input',
  'label',
  'list',
  'login',
  'modal',
  'navigation',
  'pagination',
  'password',
  'progress-bar',
  'radio',
  'schematics',
  'select',
  'sidenav',
  'signpost',
  'spinner',
  'stack-view',
  'stepper',
  'table',
  'tabs',
  'textarea',
  'timeline',
  'toggle',
  'tooltip',
  'tree-view',
  'vertical-nav',
  'wizard',
  'icons',
  'range',
  'website',
  'panel',
];

// Merging what @commitlint/config-convensional has with our new two types of commit
const types = ['a11y', 'release'].concat(commitLintConfig.rules['type-enum'][2]);

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [2, 'always'],
    'type-enum': [2, 'always', types],
    'header-max-length': [2, 'always', 100],
  },
};
