version: 2
# Jobs
jobs:
  build:
    docker:
      - image: circleci/node:dubnium-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - modules{{checksum "package.json"}}
            - modules
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: modules{{checksum "package.json"}}
      - run: npm run build:ci
# Workflows
workflows:
  version: 2
  test:
    jobs:
      - build