name: Dev

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn build:libs && yarn angular:dev:build
      - run: yarn angular:dev:deploy

    env:
      CI: true
      NETLIFY_SITE_ID: 03fce0dd-9568-4ab2-a3ea-211d856989db
