name: Dev

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'vmware/clarity'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ github.base_ref }}
      - run: yarn install
      - run: yarn build:angular
      - run: yarn build:dev
      - run: yarn build:dev:deploy

    env:
      CI: true
      NETLIFY_SITE_ID: 03fce0dd-9568-4ab2-a3ea-211d856989db
