name: Website

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'vmware/clarity'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}-${{ github.base_ref }}
      - run: npm install
      - run: npm run build:angular
      - run: npm run build:website
      - run: npm run deploy:website

    env:
      CI: true
      NETLIFY_SITE_ID: 1d483e6d-5fed-4f6d-a085-420cb0f921c3
